package:
  name: elastic
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') | replace('v','',1) }}

source:
  git_url: https://github.com/jochym/Elastic.git
  git_branch: {{ environ.get('GIT_BRANCH','master') }}

build:
  preserve_egg_dir: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - elastic = elastic:main
    #
    # Would create an entry point called elastic that calls elastic.main()
    - elastic = elastic.cli.elastic:cli


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - future
    - setuptools
    - setuptools_scm
    - sphinx
    - docutils
    - click

  run:
    - python
    - ase
    - numpy
    - scipy
    - spglib
    - future
    - click

test:
  source_files:
    - test
    - tests
  requires:
    - hypothesis
  imports:
    - elastic
  commands:
    - python -m unittest discover -s test
    - elastic --version
    - elastic -v --cij proc tests/data/calc-cij_*/vasprun.xml


about:
  home: https://github.com/jochym/Elastic
  license: GPLv3
  summary: 'Extension for ASE to calculate elastic constants'

