name: Build and test
on: workflow_call

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: "3.x"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: python3 -m build

    - name: Test 
      run: |
        python3 -m pip install hypothesis
        python3 -m pip install dist/elastic*.whl
        elastic --version
        python3 -m unittest discover -s test -b
        elastic -v --cij proc tests/data/calc-cij_*/vasprun.xml
        elastic -v --eos proc tests/data/calc-eos_*/vasprun.xml

    - name: Store the distribution packages
      uses: actions/upload-artifact@main
      with:
        name: python-package-distributions
        path: dist/

  